### ISSUE TITLE
Incompatible with GLFW3

### ISSUE THREAD

**Issue by kstrafe** [hsalokor/rkt-glfw#1]
Several functions like glfwOpenWindow have been renamed to glfwCreateWindow.

**Comment by kstrafe** [comment]
See PR https://github.com/hsalokor/rkt-glfw/pull/2

**Comment by hsalokor** [comment]
Sorry dude! I seriously missed you PR - merging them both now, but it’s probably too late.

Again - apologies and thank you for PR!

**Comment by kstrafe** [comment]
What do you mean it's too late? Good you noticed now so racket has modern GLFW bindings :)

**Comment by hsalokor** [comment]
Good point :)
